[build]
  command = "hugo --gc --minify -D -b $URL"
  publish = "public"

[build.environment]
HUGO_VERSION = "0.147.8"
HUGO_THEMESDIR = "../.."
HUGO_THEME = "repo"
TZ = "North America/Montreal"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "cd exampleSite && hugo --gc --minify -D -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "cd exampleSite && hugo --gc --minify -D -b $DEPLOY_PRIME_URL"
